package gui;

import db.DatabaseHandler;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paolo
 */
public class HomeGUI extends javax.swing.JFrame {
    
    DatabaseHandler db;

    /**
     * Creates new form HomeGUI
     */
    public HomeGUI() {
         db = new DatabaseHandler();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        actions = new javax.swing.JPanel();
        btnFornitori = new javax.swing.JButton();
        btnProdotti = new javax.swing.JButton();
        btnMovimenti = new javax.swing.JButton();
        btnGiacenza = new javax.swing.JButton();
        btnMostraMovimenti = new javax.swing.JButton();
        btnEsci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("main"); // NOI18N
        setResizable(false);

        title.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Gestione Magazzino");

        actions.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        actions.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        btnFornitori.setText("Inserisci Fornitore");
        btnFornitori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFornitoriMouseClicked(evt);
            }
        });
        actions.add(btnFornitori);

        btnProdotti.setText("Inserisci Prodotti");
        btnProdotti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdottiMouseClicked(evt);
            }
        });
        actions.add(btnProdotti);

        btnMovimenti.setText("Inserisci Movimenti");
        btnMovimenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovimentiMouseClicked(evt);
            }
        });
        actions.add(btnMovimenti);

        btnGiacenza.setText("Giacenza Attuale");
        actions.add(btnGiacenza);

        btnMostraMovimenti.setText("Mostra Movimenti");
        actions.add(btnMostraMovimenti);

        btnEsci.setText("Esci");
        btnEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsciActionPerformed(evt);
            }
        });
        actions.add(btnEsci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(actions, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        confermaUscita();
    }//GEN-LAST:event_btnEsciActionPerformed

    private void btnFornitoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFornitoriMouseClicked
       InserisciFornitore iFpanel = new InserisciFornitore(db);
       iFpanel.setVisible(true);
    }//GEN-LAST:event_btnFornitoriMouseClicked

    private void btnProdottiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdottiMouseClicked
        InserisciProdotto iPpanel = new InserisciProdotto(db);
        iPpanel.setVisible(true);
    }//GEN-LAST:event_btnProdottiMouseClicked

    private void btnMovimentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovimentiMouseClicked
        InserisciMovimento iMpanel = new InserisciMovimento(db);
        iMpanel.setVisible(true);
    }//GEN-LAST:event_btnMovimentiMouseClicked

    private void confermaUscita() {
        int choice = JOptionPane.showConfirmDialog(this,
                "Sei sicuro di voler uscire?",
                "Conferma Uscita", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actions;
    private javax.swing.JButton btnEsci;
    private javax.swing.JButton btnFornitori;
    private javax.swing.JButton btnGiacenza;
    private javax.swing.JButton btnMostraMovimenti;
    private javax.swing.JButton btnMovimenti;
    private javax.swing.JButton btnProdotti;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
