CREATE TABLE ATTORI(
	Codice INT PRIMARY KEY,
	Cognome VARCHAR(255),
	Nome VARCHAR(255)
);
CREATE TABLE CASSAPRODUTTRICI(
	Nome VARCHAR(255) PRIMARY KEY,
	Sede VARCHAR(255)
);
CREATE TABLE FILM(
	Titolo VARCHAR(255) PRIMARY KEY,
	Regista VARCHAR(255),
	Anno INT,
	NomeProd VARCHAR(255),
	FOREIGN KEY NomeProd REFERENCES CASSAPRODUTTRICI(Nome)
);
CREATE TABLE ATTORIFILM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Attore INT,
	FIlm VARCHAR(255),
	FOREIGN KEY Attore REFERENCES ATTORI(Codice),
	FOREIGN KEY Film REFERENCES Film(Titolo)	
);
CREATE TABLE ZONE(
	Codice INT PRIMARY KEY,
	Nome VARCHAR(255)
);
CREATE TABLE CINEMA(
	Nome VARCHAR(255) PRIMARY KEY,
	Orario TIME,
	Tel VARCHAR(20),
	Film VARCHAR(255),
	Zona INT,
	FOREIGN KEY Film REFERENCES FILM(Titolo),
	FOREIGN KEY Film REFERENCES Zone(Codice)
);

ALTER TABLE FILM ADD COLUMN Genere VARCHAR(255);
ALTER TABLE FILM DROP COLUMN Anno;
